services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./shared/uploads:/shared/uploads
      - ./processor:/app/processor
    depends_on:
      - processor

  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    volumes:
      - ./shared/uploads:/shared/uploads
    ports:
      - "5001:5001"
